/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackToTop: typeof import('./components/BackToTop.vue')['default']
    FilterBar: typeof import('./components/FilterBar.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreForm: typeof import('./components/ScoreForm.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheNavigation: typeof import('./components/TheNavigation.vue')['default']
    WOption: typeof import('./components/ui/WOption.vue')['default']
    WPopconfirm: typeof import('./components/ui/WPopconfirm.vue')['default']
    WRadioButton: typeof import('./components/ui/WRadioButton.vue')['default']
    WRadioGroup: typeof import('./components/ui/WRadioGroup.vue')['default']
    WSelect: typeof import('./components/ui/WSelect.vue')['default']
  }
}
